/**
 * FtHoF Planner v6b
 * translate.ts
 *
 * translation definition
 */


/** language list */
type Lang = (
	| "EN"
	| "FR" | "DE" | "NL" | "CS" | "PL" | "IT" | "ES" | "PT-BR"
	| "JA" | "ZH-CN" | "KO"
	| "RU"
);

/** translation dictionary */
type EnToLocalWordDict = {
	"Lucky": string;
	"Ruin": string;
	"Cookie Chain": string;
	"Frenzy": string;
	"Elder Frenzy": string;
	"Clot": string;
	"Cursed Finger": string;
	"Click Frenzy": string;
	"Cookie Storm": string;
	"Sugar Lump": string;

	"Conjure Baked Goods": string;
	"Force the Hand of Fate": string;
	"Stretch Time": string;
	"Spontaneous Edifice": string;
	"Haggler's Charm": string;
	"Summon Crafty Pixies": string;
	"Gambler's Fever Dream": string;
	"Resurrect Abomination": string;
	"Diminish Ineptitude": string;

	"Breath of Milk": string;
	"Dragon Cursor": string;
	"Elder Battalion": string;
	"Reaper of Fields": string;
	"Earth Shatterer": string;
	"Master of the Armory": string;
	"Fierce Hoarder": string;
	"Dragon God": string;
	"Arcane Aura": string;
	"Dragonflight": string;
	"Ancestral Metamorphosis": string;
	"Unholy Dominion": string;
	"Epoch Manipulator": string;
	"Mind Over Matter": string;
	"Radiant Appetite": string;
	"Dragon's Fortune": string;
	"Dragon's Curve": string;
	"Reality Bending": string;
	"Dragon Orbs": string;
	"Supreme Intellect": string;
	"Dragon Guts": string;

	"Cookie Storm Drop": string;
	"Drop": string;
	"Building Special": string;
	"Blab": string;
};


// code for getting translated words in each languages
/*(async () => {
	// base loc() id to get translated words
	const locIds = [
		// not buff: main.js L5542, L5549, L5589
		"Lucky!", "Ruin!", "Cookie chain",

		// buff: main.js L13865
		"Frenzy", "Elder frenzy", "Clot", "Cursed finger", "Click frenzy", "Cookie storm",

		// language file L7, main.js L4520
		"sugar lump", "%1 sugar lump",

		// spell: minigameGrimoire.js L12
		"Conjure Baked Goods", "Force the Hand of Fate", "Stretch Time",
		"Spontaneous Edifice", "Haggler's Charm", "Summon Crafty Pixies",
		"Gambler's Fever Dream", "Resurrect Abomination", "Diminish Ineptitude",

		// aura: main.js L14829, L14855
		"Breath of Milk",
		"Dragon Cursor", "Elder Battalion", "Reaper of Fields", "Earth Shatterer",
		"Master of the Armory", "Fierce Hoarder", "Dragon God", "Arcane Aura",
		"Dragonflight", "Ancestral Metamorphosis", "Unholy Dominion", "Epoch Manipulator",
		"Mind Over Matter", "Radiant Appetite", "Dragon's Fortune", "Dragon's Curve",
		"Reality Bending", "Dragon Orbs", "Supreme Intellect", "Dragon Guts",

		// others
		"Buildings",
	];
	const translateds = {};
	for (const lang in Langs) {  // L305
		LoadLang('loc/'+lang+'.js?v='+Game.version, () => {
			const dict = {};
			locIds.forEach(locId => dict[locId] = loc(locId));
			translateds[lang] = dict;
		});  // L16915 > L16861 > L16868 > L87
		await new Promise((res) => setTimeout(res, 1000));
	};
	console.log(translateds);
})();*/


export const langDict: { [lang in Lang]: EnToLocalWordDict } = {
	"EN": {
		"Lucky": "Lucky",
		"Ruin": "Ruin",
		"Cookie Chain": "Cookie Chain",
		"Frenzy": "Frenzy",
		"Elder Frenzy": "Elder Frenzy",
		"Clot": "Clot",
		"Cursed Finger": "Cursed Finger",
		"Click Frenzy": "Click Frenzy",
		"Cookie Storm": "Cookie Storm",
		"Sugar Lump": "Sugar Lump",
		"Conjure Baked Goods": "Conjure Baked Goods",
		"Force the Hand of Fate": "Force the Hand of Fate",
		"Stretch Time": "Stretch Time",
		"Spontaneous Edifice": "Spontaneous Edifice",
		"Haggler's Charm": "Haggler's Charm",
		"Summon Crafty Pixies": "Summon Crafty Pixies",
		"Gambler's Fever Dream": "Gambler's Fever Dream",
		"Resurrect Abomination": "Resurrect Abomination",
		"Diminish Ineptitude": "Diminish Ineptitude",
		"Breath of Milk": "Breath of Milk",
		"Dragon Cursor": "Dragon Cursor",
		"Elder Battalion": "Elder Battalion",
		"Reaper of Fields": "Reaper of Fields",
		"Earth Shatterer": "Earth Shatterer",
		"Master of the Armory": "Master of the Armory",
		"Fierce Hoarder": "Fierce Hoarder",
		"Dragon God": "Dragon God",
		"Arcane Aura": "Arcane Aura",
		"Dragonflight": "Dragonflight",
		"Ancestral Metamorphosis": "Ancestral Metamorphosis",
		"Unholy Dominion": "Unholy Dominion",
		"Epoch Manipulator": "Epoch Manipulator",
		"Mind Over Matter": "Mind Over Matter",
		"Radiant Appetite": "Radiant Appetite",
		"Dragon's Fortune": "Dragon's Fortune",
		"Dragon's Curve": "Dragon's Curve",
		"Reality Bending": "Reality Bending",
		"Dragon Orbs": "Dragon Orbs",
		"Supreme Intellect": "Supreme Intellect",
		"Dragon Guts": "Dragon Guts",
		"Cookie Storm Drop": "Cookie Storm Drop",
		"Drop": "Drop",
		"Building Special": "Building Special",
		"Blab": "Blab",
	},
	"FR": {
		"Lucky": "Quelle chance",
		"Ruin": "Raté",
		"Cookie Chain": "Chaîne de cookies",
		"Frenzy": "Frénésie",
		"Elder Frenzy": "Frénésie des anciennes",
		"Clot": "Caillot",
		"Cursed Finger": "Doigt maudit",
		"Click Frenzy": "Frénésie de clics",
		"Cookie Storm": "Tempête de cookies",
		"Sugar Lump": "morceau de sucre",
		"Conjure Baked Goods": "Invoquer des pâtisseries",
		"Force the Hand of Fate": "Forcer la main du Destin",
		"Stretch Time": "Dilatation temporelle",
		"Spontaneous Edifice": "Édifice spontané",
		"Haggler's Charm": "Charme du marchandeur",
		"Summon Crafty Pixies": "Invoquer des lutins habiles",
		"Gambler's Fever Dream": "Rêve fébrile du parieur",
		"Resurrect Abomination": "Résurrection abominable",
		"Diminish Ineptitude": "Réduire l'inaptitude",
		"Breath of Milk": "Souffle de lait",
		"Dragon Cursor": "Curseur dragon",
		"Elder Battalion": "Bataillon ancien",
		"Reaper of Fields": "Récolteur des champs",
		"Earth Shatterer": "Brise-terre",
		"Master of the Armory": "Maître de l'armurerie",
		"Fierce Hoarder": "Entasseur féroce",
		"Dragon God": "Dieu dragon",
		"Arcane Aura": "Aura arcanique",
		"Dragonflight": "Vol de dragon",
		"Ancestral Metamorphosis": "Métamorphose ancestrale",
		"Unholy Dominion": "Domination impie",
		"Epoch Manipulator": "Manipulateur d'époque",
		"Mind Over Matter": "L'esprit prévaut sur la matière",
		"Radiant Appetite": "Appétit radieux",
		"Dragon's Fortune": "Fortune de dragon",
		"Dragon's Curve": "Courbe du dragon",
		"Reality Bending": "Distorsion de réalité",
		"Dragon Orbs": "Orbes de dragon",
		"Supreme Intellect": "« Intelligence suprême »,",
		"Dragon Guts": "Tripes de dragon",
		"Cookie Storm Drop": "Goutte de la tempête de cookies",
		"Drop": "Goutte",
		"Building Special": "Spécial constructions",
		"Blab": "Bla",
	},
	"DE": {
		"Lucky": "Glück",
		"Ruin": "Ruin",
		"Cookie Chain": "Keks-Kette",
		"Frenzy": "Rausch",
		"Elder Frenzy": "Ältestenrausch",
		"Clot": "Gerinnsel",
		"Cursed Finger": "Verfluchter Finger",
		"Click Frenzy": "Klickrausch",
		"Cookie Storm": "Kekssturm",
		"Sugar Lump": "Würfelzucker",
		"Conjure Baked Goods": "Backwaren herbeizaubern",
		"Force the Hand of Fate": "Die Hand des Schicksals erzwingen",
		"Stretch Time": "Zeitdehnung",
		"Spontaneous Edifice": "Spontanes Bauwerk",
		"Haggler's Charm": "Feilscherkönig",
		"Summon Crafty Pixies": "Beschwöre handwerkliche Feen",
		"Gambler's Fever Dream": "Fiebertraum eines Spielers",
		"Resurrect Abomination": "Abscheulichkeit wiederauferstehen lassen",
		"Diminish Ineptitude": "Ungeschicklichkeit vermindern",
		"Breath of Milk": "Hauch von Milch",
		"Dragon Cursor": "Drachen Cursor",
		"Elder Battalion": "Ältestenbataillon",
		"Reaper of Fields": "Sensenmann der Felder",
		"Earth Shatterer": "Erdzerstörer",
		"Master of the Armory": "Meister der Waffenkammer",
		"Fierce Hoarder": "Wilder Hamsterer",
		"Dragon God": "Drachengott",
		"Arcane Aura": "Arkane Aura",
		"Dragonflight": "Flug des Drachen",
		"Ancestral Metamorphosis": "Metamorphose der Vorfahren",
		"Unholy Dominion": "Unheilige Herrschaft",
		"Epoch Manipulator": "Epochenmanipulator",
		"Mind Over Matter": "Augen zu und durch",
		"Radiant Appetite": "Strahlender Appetit",
		"Dragon's Fortune": "Glück des Drachen",
		"Dragon's Curve": "Drachenbogen",
		"Reality Bending": "Wirklichkeitsverbiegung",
		"Dragon Orbs": "Drachenkugeln",
		"Supreme Intellect": "Höchster Intellekt",
		"Dragon Guts": "Dracheneingeweide",
		"Cookie Storm Drop": "Kekssturm-Tropfen",
		"Drop": "Tropfen",
		"Building Special": "Gebäude-Spezial",
		"Blab": "Blabla",
	},
	"NL": {
		"Lucky": "Geluk",
		"Ruin": "Geruïneerd",
		"Cookie Chain": "Koekjesketen",
		"Frenzy": "Frenzy",
		"Elder Frenzy": "Ouderlingenfrenzy",
		"Clot": "Prop",
		"Cursed Finger": "Vervloekte Vinger",
		"Click Frenzy": "Klikfrenzy",
		"Cookie Storm": "Koekjesstorm",
		"Sugar Lump": "Suikerklontje",
		"Conjure Baked Goods": "Bezweer Gebakken Waren",
		"Force the Hand of Fate": "Forceer de Hand der Lot",
		"Stretch Time": "Strektijd",
		"Spontaneous Edifice": "Spontaan Bouwwerk",
		"Haggler's Charm": "Charme van de Onderhandelaar",
		"Summon Crafty Pixies": "Roep Ijverige Feeën Op",
		"Gambler's Fever Dream": "Koortsachtige Droom van de Gokker",
		"Resurrect Abomination": "Gruwel Opnieuw Tot Leven Brengen",
		"Diminish Ineptitude": "Onbekwaamheid Verkleinen",
		"Breath of Milk": "Melkadem",
		"Dragon Cursor": "Drakencursor",
		"Elder Battalion": "Omabataljon",
		"Reaper of Fields": "Veldoogster",
		"Earth Shatterer": "Grondverwoester",
		"Master of the Armory": "Meester van de Wapens",
		"Fierce Hoarder": "Woeste Verzamelaar",
		"Dragon God": "Drakengod",
		"Arcane Aura": "Mysterieuze Aura",
		"Dragonflight": "Drakenvlucht",
		"Ancestral Metamorphosis": "Oermetamorfose",
		"Unholy Dominion": "Heidense Heerschappij",
		"Epoch Manipulator": "Tijdperkmanipulator",
		"Mind Over Matter": "Geest Voor Materie",
		"Radiant Appetite": "Stralende Eetlust",
		"Dragon's Fortune": "Drakengeluk",
		"Dragon's Curve": "Drakencurve",
		"Reality Bending": "Andere Realiteit",
		"Dragon Orbs": "Drakenbollen",
		"Supreme Intellect": "Superieur Intellect",
		"Dragon Guts": "Drakendarmen",
		"Cookie Storm Drop": "Koekjesstormdruppel",
		"Drop": "Druppel",
		"Building Special": "Gebouwen-special",
		"Blab": "Blabla",
	},
	"CS": {
		"Lucky": "Šťastlivec",
		"Ruin": "Ztráta",
		"Cookie Chain": "Keksový řetězec",
		"Frenzy": "Frenzy",
		"Elder Frenzy": "Starší Frenzy",
		"Clot": "Sraženina",
		"Cursed Finger": "Prokletý prst",
		"Click Frenzy": "Klikněte na Frenzy",
		"Cookie Storm": "Sušenková bouře",
		"Sugar Lump": "cukrová hrudka",
		"Conjure Baked Goods": "Vyvolat Pečivo",
		"Force the Hand of Fate": "Vymoct Ruku osudu",
		"Stretch Time": "Čas",
		"Spontaneous Edifice": "Spontánní stavba",
		"Haggler's Charm": "Smlouvačův přívěsek",
		"Summon Crafty Pixies": "Vyvolat Mazané skřítky",
		"Gambler's Fever Dream": "Sen hráčské horečky",
		"Resurrect Abomination": "Vzkřísit ohavnost",
		"Diminish Ineptitude": "Zmenšit neschopnost",
		"Breath of Milk": "Mléčný dech",
		"Dragon Cursor": "Dračí kurzor",
		"Elder Battalion": "Starší batalion",
		"Reaper of Fields": "Žnec polí",
		"Earth Shatterer": "Drtič země",
		"Master of the Armory": "Mistr zbrojnice",
		"Fierce Hoarder": "Zběsilý hrabivec",
		"Dragon God": "Dračí bůh",
		"Arcane Aura": "Tajemná aura",
		"Dragonflight": "Dračí let",
		"Ancestral Metamorphosis": "Starodávná metamorfóza",
		"Unholy Dominion": "Nesvatá vláda",
		"Epoch Manipulator": "Epochální manipulátor",
		"Mind Over Matter": "Vítězství ducha nad hmotou",
		"Radiant Appetite": "Oslnivý apetit",
		"Dragon's Fortune": "Dračí bohatství",
		"Dragon's Curve": "Dračí zákruta",
		"Reality Bending": "Ohnutí reality",
		"Dragon Orbs": "Dračí koule",
		"Supreme Intellect": "Nejvyšší intelekt",
		"Dragon Guts": "Dračí vnitřnosti",
		"Cookie Storm Drop": "Kapka sušenkové bouře",
		"Drop": "Kapka",
		"Building Special": "Speciál budov",
		"Blab": "Kecy",
	},
	"PL": {
		"Lucky": "Szczęściarz",
		"Ruin": "Tragedia",
		"Cookie Chain": "Ciastkowy łańcuch",
		"Frenzy": "Szał",
		"Elder Frenzy": "Szał starszyzny",
		"Clot": "Zakrzep",
		"Cursed Finger": "Przeklęty palec",
		"Click Frenzy": "Szał klikania",
		"Cookie Storm": "Ciastkowa burza",
		"Sugar Lump": "grudka cukru",
		"Conjure Baked Goods": "Przyzwij Wypieki",
		"Force the Hand of Fate": "Pokieruj Ręką Przeznaczenia",
		"Stretch Time": "Rozciągnij czas",
		"Spontaneous Edifice": "Spontaniczny gmach",
		"Haggler's Charm": "Urok przekupki",
		"Summon Crafty Pixies": "Przyzwij wróżki-rzemieślniczki",
		"Gambler's Fever Dream": "Szał hazardzisty",
		"Resurrect Abomination": "Wskrześ maszkarę",
		"Diminish Ineptitude": "Redukcja niekompetencji",
		"Breath of Milk": "Oddech mleka",
		"Dragon Cursor": "Smoczy kursor",
		"Elder Battalion": "Batalion starców",
		"Reaper of Fields": "Pogromca pól",
		"Earth Shatterer": "Niszczyciel ziemi",
		"Master of the Armory": "Mistrz pancerza",
		"Fierce Hoarder": "Nieustraszony kolekcjoner",
		"Dragon God": "Smoczy bóg",
		"Arcane Aura": "Tajemnicza aura",
		"Dragonflight": "Smoczy lot",
		"Ancestral Metamorphosis": "Niebiańska metamorfoza",
		"Unholy Dominion": "Plugawe królestwo",
		"Epoch Manipulator": "Epicki manipulator",
		"Mind Over Matter": "Umysł ponad materią",
		"Radiant Appetite": "Nieposkromiony apetyt",
		"Dragon's Fortune": "Smocze szczęście",
		"Dragon's Curve": "Smocza krzywa",
		"Reality Bending": "Zakrzywianie rzeczywistości",
		"Dragon Orbs": "Smocze kule",
		"Supreme Intellect": "„Wybitny intelekt”,",
		"Dragon Guts": "Smocze wnętrzności",
		"Cookie Storm Drop": "Kropla ciastkowej burzy",
		"Drop": "Kropla",
		"Building Special": "Specjalne budynki",
		"Blab": "Gadanie",
	},
	"IT": {
		"Lucky": "Che fortuna",
		"Ruin": "Che disgrazia",
		"Cookie Chain": "Combo di biscotti",
		"Frenzy": "Frenesia",
		"Elder Frenzy": "Frenesia venerabile",
		"Clot": "Coagulo",
		"Cursed Finger": "Dita maledette",
		"Click Frenzy": "Frenesia di clic",
		"Cookie Storm": "Tempesta di biscotti",
		"Sugar Lump": "zolletta di zucchero",
		"Conjure Baked Goods": "Invoca prodotti da forno",
		"Force the Hand of Fate": "Forza la mano del destino",
		"Stretch Time": "Dilatazione temporale",
		"Spontaneous Edifice": "Edificio spontaneo",
		"Haggler's Charm": "Ciondolo del mercante",
		"Summon Crafty Pixies": "Evoca Folletti tuttofare",
		"Gambler's Fever Dream": "Sogno delirante del giocatore d'azzardo",
		"Resurrect Abomination": "Resurrezione abominevole",
		"Diminish Ineptitude": "Riduci inettitudine",
		"Breath of Milk": "Soffio di latte",
		"Dragon Cursor": "Cursore del drago",
		"Elder Battalion": "Reggimento di anziane",
		"Reaper of Fields": "Mietitore dei campi",
		"Earth Shatterer": "Frantumaterra",
		"Master of the Armory": "Maestro dell'armonia",
		"Fierce Hoarder": "Accumulatore spietato",
		"Dragon God": "Drago divino",
		"Arcane Aura": "Aura arcana",
		"Dragonflight": "Volo di drago",
		"Ancestral Metamorphosis": "Metamorfosi ancestrale",
		"Unholy Dominion": "Empio dominio",
		"Epoch Manipulator": "Orditore del tempo",
		"Mind Over Matter": "Potere della mente",
		"Radiant Appetite": "Appetito smagliante",
		"Dragon's Fortune": "Fortuna del drago",
		"Dragon's Curve": "Curva del drago",
		"Reality Bending": "Manipolazione della realtà",
		"Dragon Orbs": "Sfere del drago",
		"Supreme Intellect": "Intelletto supremo",
		"Dragon Guts": "Viscere di drago",
		"Cookie Storm Drop": "Goccia della tempesta di biscotti",
		"Drop": "Goccia",
		"Building Special": "Speciale strutture",
		"Blab": "Chiacchiera",
	},
	"ES": {
		"Lucky": "Qué suerte",
		"Ruin": "Porras",
		"Cookie Chain": "Cadena de galletas",
		"Frenzy": "Frenesí",
		"Elder Frenzy": "Frenesí de ancianas",
		"Clot": "Grumo",
		"Cursed Finger": "Dedo maldito",
		"Click Frenzy": "Frenesí de clics",
		"Cookie Storm": "Tormenta de galletas",
		"Sugar Lump": "terrón de azúcar",
		"Conjure Baked Goods": "Conjurar alimentos horneados",
		"Force the Hand of Fate": "Forzar la mano del destino",
		"Stretch Time": "Estirar el tiempo",
		"Spontaneous Edifice": "Edificación espontánea",
		"Haggler's Charm": "Encanto de regateador",
		"Summon Crafty Pixies": "Invoca duendes apañados",
		"Gambler's Fever Dream": "Sueño febril de jugador",
		"Resurrect Abomination": "Abominación desenterrada",
		"Diminish Ineptitude": "Reducir ineptitud",
		"Breath of Milk": "Aliento lechoso",
		"Dragon Cursor": "Cursor de dragón",
		"Elder Battalion": "Batallón de ancianas",
		"Reaper of Fields": "Siega campos",
		"Earth Shatterer": "Tiembla tierras",
		"Master of the Armory": "Amo de la armería",
		"Fierce Hoarder": "Fiero acaparador",
		"Dragon God": "Dios dragón",
		"Arcane Aura": "Aura arcana",
		"Dragonflight": "Vuelo de dragón",
		"Ancestral Metamorphosis": "Metamorfosis ancestral",
		"Unholy Dominion": "Dominio profano",
		"Epoch Manipulator": "Manipulador clásico",
		"Mind Over Matter": "Mente sobre materia",
		"Radiant Appetite": "Apetito radiante",
		"Dragon's Fortune": "Fortuna de dragón",
		"Dragon's Curve": "Curva de dragón",
		"Reality Bending": "Manipulación de realidad",
		"Dragon Orbs": "Orbes de dragón",
		"Supreme Intellect": "Intelecto supremo",
		"Dragon Guts": "Tripas de dragón",
		"Cookie Storm Drop": "Gota de la tormenta de galletas",
		"Drop": "Gota",
		"Building Special": "Especial de edificios",
		"Blab": "Cháchara",
	},
	"PT-BR": {
		"Lucky": "Que sorte",
		"Ruin": "Ruína",
		"Cookie Chain": "Corrente de cookies",
		"Frenzy": "Frenesi",
		"Elder Frenzy": "Frenesi Ancestral",
		"Clot": "Coágulo",
		"Cursed Finger": "Dedo amaldiçoado",
		"Click Frenzy": "Frenesi de cliques",
		"Cookie Storm": "Tempestade de cookies",
		"Sugar Lump": "torrão de açúcar",
		"Conjure Baked Goods": "Conjurar Produtos Assados",
		"Force the Hand of Fate": "Forçar a Mão do Destino",
		"Stretch Time": "Estender o Tempo",
		"Spontaneous Edifice": "Edifício Espontâneo",
		"Haggler's Charm": "Encanto do Pechinchador",
		"Summon Crafty Pixies": "Invocar Duendes Habilidosos",
		"Gambler's Fever Dream": "Alucinação do Apostador",
		"Resurrect Abomination": "Ressuscitar Abominação",
		"Diminish Ineptitude": "Reduzir a Inépcia",
		"Breath of Milk": "Bafo de Leite",
		"Dragon Cursor": "Cursor de Dragão",
		"Elder Battalion": "Batalhão de Ancestrais",
		"Reaper of Fields": "Ceifeiro de Campos",
		"Earth Shatterer": "Destruidor da Terra",
		"Master of the Armory": "Mestre do Arsenal",
		"Fierce Hoarder": "Acumulador Ávido",
		"Dragon God": "Deus Dragão",
		"Arcane Aura": "Aura Arcana",
		"Dragonflight": "Voo do Dragão",
		"Ancestral Metamorphosis": "Metamorfose Ancestral",
		"Unholy Dominion": "Domínio Profano",
		"Epoch Manipulator": "Manipulador de Época",
		"Mind Over Matter": "Mente Sobre Matéria",
		"Radiant Appetite": "Apetite Radiante",
		"Dragon's Fortune": "Fortuna de Dragão",
		"Dragon's Curve": "Curva de Dragão",
		"Reality Bending": "Dobrando a Realidade",
		"Dragon Orbs": "Orbes de Dragão",
		"Supreme Intellect": "Intelecto Supremo",
		"Dragon Guts": "Intestino de dragão",
		"Cookie Storm Drop": "Gota da tempestade de cookies",
		"Drop": "Gota",
		"Building Special": "Especial construções",
		"Blab": "Papo",
	},
	"JA": {
		"Lucky": "ラッキー",
		"Ruin": "台無し",
		"Cookie Chain": "クッキーチェーン",
		"Frenzy": "フィーバー",
		"Elder Frenzy": "エルダーフィーバー",
		"Clot": "障害発生",
		"Cursed Finger": "呪われた指",
		"Click Frenzy": "クリックフィーバー",
		"Cookie Storm": "クッキー乱舞",
		"Sugar Lump": "砂糖玉",
		"Conjure Baked Goods": "焼き菓子に魔法をかける",
		"Force the Hand of Fate": "運命を押し付ける",
		"Stretch Time": "ストレッチの時間",
		"Spontaneous Edifice": "自然発生の殿堂",
		"Haggler's Charm": "値切り屋の呪文",
		"Summon Crafty Pixies": "狡猾なピクシーを召喚",
		"Gambler's Fever Dream": "ギャンブラーの熱の夢",
		"Resurrect Abomination": "忌まわしき復活",
		"Diminish Ineptitude": "愚劣の減少",
		"Breath of Milk": "ミルクの吐息",
		"Dragon Cursor": "ドラゴンカーソル",
		"Elder Battalion": "エルダーの大隊",
		"Reaper of Fields": "収穫者",
		"Earth Shatterer": "大地を耕す者",
		"Master of the Armory": "武装マスター",
		"Fierce Hoarder": "守銭奴",
		"Dragon God": "竜の神",
		"Arcane Aura": "神秘的なオーラ",
		"Dragonflight": "ドラゴンフライト",
		"Ancestral Metamorphosis": "継承されたメタモルフォーゼ",
		"Unholy Dominion": "汚れた支配",
		"Epoch Manipulator": "世紀の業師",
		"Mind Over Matter": "強靭な精神力",
		"Radiant Appetite": "果てしない食欲",
		"Dragon's Fortune": "ドラゴンの運",
		"Dragon's Curve": "ドラゴンの曲線",
		"Reality Bending": "現実の歪曲",
		"Dragon Orbs": "ドラゴンオーブ",
		"Supreme Intellect": "最高峰の知性、",
		"Dragon Guts": "ドラゴンのはらわた",
		"Cookie Storm Drop": "クッキー乱舞の雫",
		"Drop": "雫",
		"Building Special": "建物スペシャル",
		"Blab": "おしゃべり",
	},
	"ZH-CN": {
		"Lucky": "好运气",
		"Ruin": "破财",
		"Cookie Chain": "饼干连锁",
		"Frenzy": "狂热",
		"Elder Frenzy": "长者狂热",
		"Clot": "凝块",
		"Cursed Finger": "被诅咒的手指",
		"Click Frenzy": "点击狂热",
		"Cookie Storm": "饼干风暴",
		"Sugar Lump": "糖块",
		"Conjure Baked Goods": "召唤烘焙食品",
		"Force the Hand of Fate": "逼迫命运之手",
		"Stretch Time": "延长时间",
		"Spontaneous Edifice": "自发大厦",
		"Haggler's Charm": "讨价还价者的魅力",
		"Summon Crafty Pixies": "召唤狡猾的小精灵",
		"Gambler's Fever Dream": "赌徒狂热的梦想",
		"Resurrect Abomination": "复活可憎",
		"Diminish Ineptitude": "减少无能",
		"Breath of Milk": "牛奶之息",
		"Dragon Cursor": "龙指针",
		"Elder Battalion": "元老队伍",
		"Reaper of Fields": "田野收割者",
		"Earth Shatterer": "大地粉碎者",
		"Master of the Armory": "护甲大师",
		"Fierce Hoarder": "凶猛囤积者",
		"Dragon God": "龙神",
		"Arcane Aura": "秘术光环",
		"Dragonflight": "飞龙在天",
		"Ancestral Metamorphosis": "祖传蜕变",
		"Unholy Dominion": "邪恶仆从",
		"Epoch Manipulator": "纪元操纵者",
		"Mind Over Matter": "心胜于物",
		"Radiant Appetite": "光源需求",
		"Dragon's Fortune": "龙之幸运",
		"Dragon's Curve": "龙之曲线",
		"Reality Bending": "现实扭曲",
		"Dragon Orbs": "龙之宝珠",
		"Supreme Intellect": "“最高智慧”，",
		"Dragon Guts": "龙胆",
		"Cookie Storm Drop": "饼干风暴之滴",
		"Drop": "滴",
		"Building Special": "建筑特辑",
		"Blab": "唠叨",
	},
	"KO": {
		"Lucky": "행운",
		"Ruin": "파멸",
		"Cookie Chain": "쿠키 체인",
		"Frenzy": "프렌지",
		"Elder Frenzy": "장로 프렌지",
		"Clot": "응고",
		"Cursed Finger": "저주받은 손가락",
		"Click Frenzy": "클릭 프렌지",
		"Cookie Storm": "쿠키 폭풍",
		"Sugar Lump": "각설탕",
		"Conjure Baked Goods": "제과 마법",
		"Force the Hand of Fate": "운명의 손을 움직이다",
		"Stretch Time": "시간 연장",
		"Spontaneous Edifice": "자발적 체계",
		"Haggler's Charm": "흥정꾼의 매력",
		"Summon Crafty Pixies": "건설 요정 소환",
		"Gambler's Fever Dream": "도박꾼의 열에 들뜬 꿈",
		"Resurrect Abomination": "이물 부활",
		"Diminish Ineptitude": "미숙함 감소",
		"Breath of Milk": "우유의 숨결",
		"Dragon Cursor": "드래곤 커서",
		"Elder Battalion": "장로 대대",
		"Reaper of Fields": "들판의 수확자",
		"Earth Shatterer": "대지 분쇄자",
		"Master of the Armory": "무기고의 달인",
		"Fierce Hoarder": "맹렬한 수집가",
		"Dragon God": "드래곤 신",
		"Arcane Aura": "신비로운 오라",
		"Dragonflight": "드래곤 비행",
		"Ancestral Metamorphosis": "선조의 변형",
		"Unholy Dominion": "불경한 영지",
		"Epoch Manipulator": "시대의 조종자",
		"Mind Over Matter": "정신력 문제",
		"Radiant Appetite": "빛나는 식성",
		"Dragon's Fortune": "드래곤의 행운",
		"Dragon's Curve": "드래곤의 술책",
		"Reality Bending": "현실 왜곡",
		"Dragon Orbs": "드래곤 오브",
		"Supreme Intellect": "최고의 지성",
		"Dragon Guts": "드래곤 똥배",
		"Cookie Storm Drop": "쿠키 폭풍의 물방울",
		"Drop": "물방울",
		"Building Special": "건물 스페셜",
		"Blab": "수다",
	},
	"RU": {
		"Lucky": "Повезло",
		"Ruin": "Разорение",
		"Cookie Chain": "Цепочка печенья",
		"Frenzy": "Безумие",
		"Elder Frenzy": "Безумие старушек",
		"Clot": "Сгусток",
		"Cursed Finger": "Проклятый палец",
		"Click Frenzy": "Кликательное безумие",
		"Cookie Storm": "Шторм печенек",
		"Sugar Lump": "кусочек сахара",
		"Conjure Baked Goods": "Наколдовать выпечку",
		"Force the Hand of Fate": "Тянуть руку судьбы",
		"Stretch Time": "Замедление времени",
		"Spontaneous Edifice": "Спонтанное строение",
		"Haggler's Charm": "Удача торговца",
		"Summon Crafty Pixies": "Призыв умелых фей",
		"Gambler's Fever Dream": "Мечта азартного игрока",
		"Resurrect Abomination": "Воскресить чудовище",
		"Diminish Ineptitude": "Снизить неумение",
		"Breath of Milk": "Молочное дыхание",
		"Dragon Cursor": "Курсор дракона",
		"Elder Battalion": "Батальон старушек",
		"Reaper of Fields": "Жнец полей",
		"Earth Shatterer": "Землекрушитель",
		"Master of the Armory": "Мастер оружия",
		"Fierce Hoarder": "Свирепый хранитель",
		"Dragon God": "Драконий бог",
		"Arcane Aura": "Мистическая аура",
		"Dragonflight": "Полет дракона",
		"Ancestral Metamorphosis": "Наследственная метаморфоза",
		"Unholy Dominion": "Нечестивое владычество",
		"Epoch Manipulator": "Манипулятор эпохи",
		"Mind Over Matter": "Усилие воли",
		"Radiant Appetite": "Сияющий аппетит",
		"Dragon's Fortune": "Удача дракона",
		"Dragon's Curve": "Кривая дракона",
		"Reality Bending": "Искажение реальности",
		"Dragon Orbs": "Сферы дракона",
		"Supreme Intellect": "Высший интеллект",
		"Dragon Guts": "Драконьи потроха",
		"Cookie Storm Drop": "Капля шторма печенек",
		"Drop": "Капля",
		"Building Special": "Специальное строение",
		"Blab": "Болтовня",
	},
};
